export const useDefaultProps = () => ({
    modelValue: () => [],
    display: 'form' as 'form',
    labelPosition: 'right' as 'right',
    labelWidth: 'auto' as 'auto',
    border: false,
    stripe: false,
    // theme: 'divider',
    // showTableHeader: true,
    showSerial: true,
    layout: 'auto' as 'auto',
    leftFixedColumns: 0,
    fixedOperation: true,
    showOperation: true,
    serialName: '项目',
    operationWidth: '100px',
    // customColumns: true,
    expand: true,
    showCopyButton: false,
    copyButtonLabel: '复制',
    showDeleteButton: true,
    deleteButtonLabel: '删除',
    confirmDelete: true,
    sortable: false,
    upButtonLabel: '上移',
    downButtonLabel: '下移',
    addButtonLabel: '新增一项',
    slotFromParent: false,
    // addButtonStatus: 'active',
    hideAddBtn: false,
    pageSize: 10,
    max: 50
})
