import './assets/styles/index.scss'
import { default as install } from './register'
export * from './register'
export * from './setting'

export { default as FunctionalComponent } from './FunctionalComponent'
export * from './GAddress'
export * from './GBaseDrawerContent'
export * from './GBaseModule'
export * from './GBaseModuleV2'
export * from './GButtonGroup'
export * from './GChart'
export * from './GCollapse'
export * from './GDButton'
export * from './GFigureInput'
export * from './GFilePreview'
export * from './GForm'
export * from './GFormGenerate'
export * from './GHintBox'
export * from './GIcon'
export * from './GIconPicker'
export * from './GInfoSA'
export * from './GIrregularTable'
export * from './GLodingShade'
export * from './GModal'
export * from './GSelectTree'
export * from './GTable'
export * from './GTabs'
export * from './GTransfer'
export * from './GTransferTree'
export * from './GTree'
export * from './GUpload'
export * from './GUploadFolder'
export * from './JnEditor'

export default install
